# -*- coding: utf-8 -*-
"""Тамагочи. мини-игры и взаимодействие

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ihmyYeoTm5mZQJwrjdBz7tvY_9cmjmyP
"""

import pygame
import random


ball_active = False
b_rect = None             # прямоугольник мяча
b_speed_x = 5
b_speed_y = 5
b_hits = 0
b_hits_needed = 10
b_size = 40

def start_ball_game(pet_center_x, pet_center_y):
    global ball_active, b_rect, b_speed_x, b_speed_y, b_hits

    ball_active = True
    ball_hits = 0

    b_rect = pygame.Rect(pet_center_x - b_size//2,
                            pet_center_y - b_size//2 - 50,
                            b_size, b_size)

    b_speed_x = random.choice([-5, -4, 4, 5])
    b_speed_y = random.choice([-5, -4, 4, 5])

def update_ball(screen_width, screen_height):
    global b_rect, b_speed_x, b_speed_y, ball_active

    if not ball_active:
        return

    b_rect.x += b_speed_x
    b_rect.y += b_speed_y

    # Отскок от стен
    if b_rect.left <= 0 or b_rect.right >= screen_width:
        b_speed_x = -b_speed_x
    if b_rect.top <= 0 or b_rect.bottom >= screen_height:
        b_speed_y = -b_speed_y

def ball_click(mouse_pos):
    global b_hits, b_speed_x, b_speed_y, b_rect, b_size

    if not ball_active:
        return False

    if b_rect.collidepoint(mouse_pos):
        b_hits += 1

        # отлетает при клике
        b_speed_x += random.choice([-2, -1, 1, 2])
        b_speed_y += random.choice([-2, -1, 1, 2])

        # Не даём улететь слишком быстро
        if b_speed_x > 12: b_speed_x = 12
        if b_speed_x < -12: b_speed_x = -12
        if b_speed_y > 12: b_speed_y = 12
        if b_speed_y < -12: b_speed_y = -12

        return True
    return False

def check_ball_game_complete():
    """Проверяет, закончилась ли игра. Возвращает кол-во награды (0 если не закончилась)"""
    global ball_active

    if not ball_active:
        return 0

    if b_hits >= b_needed:
        ball_active = False
        return 20
    return 0

def draw_ball_game(screen, font):
    """Рисует игру с мячиком на экране"""
    if not ball_active:
        return None

    screen_width = screen.get_width()
    screen_height = screen.get_height()

    # Рисуем мяч
    pygame.draw.ellipse(screen, (255, 100, 100), b_rect)

    # Счётчик
    hits_text = font.render(f"Попаданий: {b_hits}/{b_needed}", True, (255, 255, 255))
    screen.blit(score_text, (20, 20))

    # Инструкция
    help_text = font.render("Кликай по красному мячу!", True, (255, 255, 255))
    screen.blit(help_text, (screen_width//2 - 130, 20))

    # Кнопка выхода (крестик)
    exit_rect = pygame.Rect(screen_width - 50, 20, 30, 30)
    pygame.draw.rect(screen, (255, 100, 100), exit_rect)
    exit_text = font.render("X", True, (255, 255, 255))
    screen.blit(exit_text, (screen_width - 42, 22))

    return exit_rect

def is_ball_game_active():
    return ball_active

def stop_ball_game():
    """Принудительно остановить игру"""
    global ball_active
    ball_active = False

import pygame
import random

cleaning_active = False
bubbles = []
clean_start = 0
clean_score = 0
cleaning_game_duration = 10
bubble_lives = 1500       # (в миллисекундах)пузырёк живёт 1.5 сek

def start_cleaning_game():
    global cleaning_active, bubbles, clean_start, clean_score

    cleaning_active = True
    bubbles = []
    clean_start = pygame.time.get_ticks()
    clean_score = 0

    for _ in range(5):
        spawn_bubble()

def spawn_bubble():
    """новый пузырёк в случайном месте"""
    global bubbles

    size = random.randint(20, 45)

    # Случайная позиция (не прилипает к краям)
    x = random.randint(50, 750 - size)
    y = random.randint(50, 550 - size)

    speed_x = random.uniform(-1.5, 1.5)
    speed_y = random.uniform(-1.5, 1.5)

    bubble = {'rect': pygame.Rect(x, y, size, size),
        'speed_x': speed_x,
        'speed_y': speed_y,
        'spawn_time': pygame.time.get_ticks(),
        'size': size}
    bubbles.append(bubble)

def update_cleaning_game(screen_width, screen_height):
    global cleaning_active, bubbles, clean_score

    if not cleaning_active:
        return False

    now = pygame.time.get_ticks()

    time_passed = (now - clean_start_time) / 1000  # сек
    if time_passed >= cleaning_game_duration:
        cleaning_active = False
        return True

    # новые пузырьки каждые 0.3 сек
    if random.randint(1, 20) == 1:  # вероятность появления
        if len(bubbles) < 25:  # <= 25 пузырьков на экране
            spawn_bubble()

    # Обновление пузырьков и удаление старых
    for bubble in bubbles[:]:  # [:] это копия списка для безопасного удаления
        bubble['rect'].x += bubble['speed_x']
        bubble['rect'].y += bubble['speed_y']

        # Отскок от стен
        if bubble['rect'].left <= 0 or bubble['rect'].right >= screen_width:
            bubble['speed_x'] = -bubble['speed_x']
        if bubble['rect'].top <= 0 or bubble['rect'].bottom >= screen_height:
            bubble['speed_y'] = -bubble['speed_y']

        if now - bubble['spawn_time'] > bubble_lives:
            bubbles.remove(bubble)

    return False  # игра ещё не закончилась

def bubble_click(mouse_pos):
    global bubbles, clean_score

    if not cleaning_active:
        return False

    for bubble in bubbles[:]:
        if bubble['rect'].collidepoint(mouse_pos):
            bubbles.remove(bubble)
            clean_score += 1
            return True
    return False

def draw_cleaning_game(screen, font):
    if not cleaning_active:
        return None

    screen_width = screen.get_width()
    screen_height = screen.get_height()

    for bubble in bubbles:
        size = bubble['size']
        rect = bubble['rect']

        # сам пузырёк
        pygame.draw.circle(screen, (200, 230, 255), rect.center, size // 2)
        pygame.draw.circle(screen, (100, 150, 200), rect.center, size // 2, 2)


    # Счётчик времени
    now = pygame.time.get_ticks()
    time_passed = (now - clean_start) / 1000
    time_left = max(0, cleaning_game_duration - elapsed)

    time_text = font.render(f"Время: {time_left:.1f}", True, (0, 0, 139))  # тёмно-синий
    screen.blit(time_text, (20, 20))

    # Счётчик лопнутых
    hits_text = font.render(f"Пузырьков: {clean_score}", True, (0, 0, 139))
    screen.blit(score_text, (20, 60))

    # Инструкция
    htlp_text = font.render("Лопай пузырьки, чтобы помыть питомца!", True, (0, 0, 139))
    screen.blit(inst_text, (screen_width//2 - 200, 20))

    # Кнопка выхода
    exit_rect = pygame.Rect(screen_width - 50, 20, 30, 30)
    pygame.draw.rect(screen, (255, 100, 100), exit_rect)
    exit_text = font.render("X", True, (255, 255, 255))
    screen.blit(exit_text, (screen_width - 42, 22))

    return exit_rect

def is_cleaning_active():
    return cleaning_active

def stop_cleaning_game():
    """Принудительно остановить игру-мойку"""
    global cleaning_active
    cleaning_active = False

def get_cleaning_score():
    """Сколько пузырьков лопнули (для награды)"""
    return clean_score

import pygame

last_toilet = 0
toilet_alert_shown = False
dyrty_time = 5 * 60 * 1000  # 5 игровых часов в миллисекундах (5 * 60 * 1000)

def init_toilet():
    """Инициализировать систему туалета (вызвать при старте игры)"""
    global last_toilet, toilet_alert_shown
    last_toilet = pygame.time.get_ticks()
    toilet_alert_shown = False

def take_to_toilet():
    global last_toilet, toilet_alert_shown
    last_toilet = pygame.time.get_ticks()
    toilet_alert_shown = False
    return True

def check_toilet(pet_cleanliness):
    """ Возвращает: "clean" всё чисто, "warning" скоро испачкается (за минуту до), "dirty" грязно"""
    global last_toilet, toilet_alert_shown

    now = pygame.time.get_ticks()
    time_since_last = now - last_toilet

    if time_since_last >= dyrty_time:
        return "dirty"

    # Если прошло больше dyrty_time - 60000 (за минуту до) и предупреждение не показывали
    if time_since_last >= dyrty_time - 60000 and not toilet_alert_shown:
        toilet_alert_shown = True
        return "warning"

    return "clean"

def is_pet_dirty():
    status = check_toilet(0)  # 0 не используется
    return status == "dirty"

def get_time_until_dirty():
    """возвращает 0, если уже грязный"""
    global last_toilet

    now = pygame.time.get_ticks()
    time_since_last = now - last_toilet

    if time_since_last >= dyrty_time:
        return 0

    return dyrty_time - time_since_last

def reset_toilet():
    """Сбросить систему (например, при смерти питомца)"""
    global last_toilet_time, toilet_alert_shown
    last_toilet_time = pygame.time.get_ticks()
    toilet_alert_shown = False