# -*- coding: utf-8 -*-
"""Тамагочи. магазин

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Jc3WaG2Cl_B9Var85YTv0Qfw5varNjEE
"""

import pygame

# Структура: имя товара - [цена, тип, эффект/название, описание]
ITEMS = {
    "fish": {
        "name": "🐟 Рыбка",
        "price": 20,
        "type": "food",
        "effect": "hunger",
        "value": 30,
        "desc": "Восстанавливает 30 голода"
    },
    "bone": {
        "name": "🦴 Кость",
        "price": 15,
        "type": "food",
        "effect": "hunger",
        "value": 20,
        "desc": "Восстанавливает 20 голода"
    },
    "bamboo": {
        "name": "🎋 Бамбук",
        "price": 25,
        "type": "food",
        "effect": "hunger",
        "value": 35,
        "desc": "Восстанавливает 35 голода"
    },
    "sleep_potion": {
        "name": "🧪 Зелье сна",
        "price": 50,
        "type": "energy",
        "effect": "energy",
        "value": 100,
        "desc": "Восстанавливает 100 энергии"
    },
    "hat": {
        "name": "🎩 Шляпа",
        "price": 80,
        "type": "accessory",
        "effect": "accessory",
        "value": "hat",
        "desc": "Красивая шляпа для питомца"
    },
    "glasses": {
        "name": "👓 Очки",
        "price": 60,
        "type": "accessory",
        "effect": "accessory",
        "value": "glasses",
        "desc": "Стильные очки"
    }
}

shop_active = False
selected = 0           # индекс в списке
item_keys = list(ITEMS.keys())  # список ключей товаров по порядку

def open_shop():
    global shop_active, selected
    shop_active = True
    selected = 0
    print("Магазин открыт!")

def close_shop():
    global shop_active
    shop_active = False
    print("Магазин закрыт")

def select_item(direction):
    """Выбрать следующий/предыдущий товар
    direction: +1 (вниз) или -1 (вверх)"""
    global selected
    selected = (selected + direction) % len(item_keys)
    print(f"Выбран: {ITEMS[item_keys[selected]]['name']}")

def buy_item(pet, game_state):
    """pet - объект питомца (с параметрами hunger, energy)
    game_state - состояние игры (coins, accessories)
    Возвращает True если купил, False если не хватило денег"""
    global shop_active

    if not shop_active:
        return False

    item_key = item_keys[selected]
    item = ITEMS[item_key]

    #хватает ли денег
    if game_state["coins"] >= item["price"]:
        # Списываем монеты
        game_state["coins"] -= item["price"]
        # Применяем эффект
        if item["type"] == "food":
            if item["effect"] == "hunger":
                pet.hunger = min(100, pet.hunger + item["value"])
                print(f"Съели {item['name']}! Голод: {pet.hunger}")

        elif item["type"] == "energy":
            if item["effect"] == "energy":
                pet.energy = min(100, pet.energy + item["value"])
                print(f"Выпили {item['name']}! Энергия: {pet.energy}")

        elif item["type"] == "accessory":
            if item["value"] not in game_state["accessories"]:
                game_state["accessories"].append(item["value"])
                print(f"Куплен аксессуар: {item['name']}")

        return True
    else:
        print(f"Не хватает денег! Нужно: {item['price']}")
        return False

def get_selected_item():
    return item_keys[selected_index]

def is_shop_active():
    return shop_active

def draw_shop(screen, font, game_state, pet):
    """Возвращает прямоугольники кнопок для обработки кликов"""
    if not shop_active:
        return None, None, None

    screen_width = screen.get_width()
    screen_height = screen.get_height()

    title_text = pygame.font.Font(None, 48)
    title = title_text.render("МАГАЗИН", True, (255, 215, 0))  # золотой
    screen.blit(title, (screen_width//2 - title.get_width()//2, 20))

    # Отображение монет
    coins_text = font.render(f"💰 Монет: {game_state['coins']}", True, (255, 215, 0))  # золотой
    screen.blit(coins_text, (20, 20))

    # Список товаров на левой половине экрана)
    list_x = 50
    list_y = 80
    item_height = 55

    for i, key in enumerate(item_keys):
        item = ITEMS[key]

        # Цвет фона выбранного товара
        if i == selected_index:
            bg_color = (70, 70, 120)
            border_color = (255, 215, 0)
            border_width = 2
        else:
            bg_color = (50, 50, 80)
            border_color = (100, 100, 150)
            border_width = 1

        # Рамка товара
        item_rect = pygame.Rect(list_x, list_y + i * item_height, 350, 50)
        pygame.draw.rect(screen, bg_color, item_rect)
        pygame.draw.rect(screen, border_color, item_rect, border_width)

        # Название и цена
        name_text = font.render(item["name"], True, (255, 255, 255))
        screen.blit(name_text, (list_x + 10, list_y + i * item_height + 5))

        price_text = font.render(f"{item['price']}💰", True, (255, 215, 0))
        screen.blit(price_text, (list_x + 250, list_y + i * item_height + 15))

        # Описание (если выбран)
        if i == selected_index:
            desc_font = pygame.font.Font(None, 24)
            desc_text = desc_font.render(item["desc"], True, (200, 200, 200))
            screen.blit(desc_text, (list_x + 10, list_y + i * item_height + 30))

    # Правая панель с инфо
    info_x = 450
    info_y = 80

    # Рамка инфо
    info_rect = pygame.Rect(info_x, info_y, 300, 350)
    pygame.draw.rect(screen, (50, 50, 80), info_rect)
    pygame.draw.rect(screen, (150, 150, 200), info_rect, 2)

    # Инфо о выбранном товаре
    selected = ITEMS[item_keys[selected_index]]

    info_title = font.render(selected["name"], True, (255, 215, 0))
    screen.blit(info_title, (info_x + 10, info_y + 10))

    info_desc = font.render(selected["desc"], True, (200, 200, 200))
    screen.blit(info_desc, (info_x + 10, info_y + 50))

    info_price = font.render(f"Цена: {selected['price']} монет", True, (255, 255, 255))
    screen.blit(info_price, (info_x + 10, info_y + 90))

    if selected["type"] == "food":
        # картинка еды

    elif selected["type"] == "energy":
        # картинка зелья

    elif selected["type"] == "accessory":
        # картинка шляпы, очков

    # Кнопка Купить(зелёная)
    buy_rect = pygame.Rect(info_x + 50, info_y + 280, 200, 45)
    pygame.draw.rect(screen, (0, 150, 0), buy_rect)
    pygame.draw.rect(screen, (0, 200, 0), buy_rect, 2)
    buy_text = font.render("КУПИТЬ", True, (255, 255, 255))
    screen.blit(buy_text, (info_x + 110, info_y + 290))

    # Кнопка Закрыть(красная)
    close_rect = pygame.Rect(screen_width - 70, 20, 50, 40)
    pygame.draw.rect(screen, (150, 0, 0), close_rect)
    pygame.draw.rect(screen, (200, 0, 0), close_rect, 2)
    close_text = font.render("X", True, (255, 255, 255))
    screen.blit(close_text, (screen_width - 53, 28))

    # Стрелки для навигации
    up_rect = pygame.Rect(list_x + 360, list_y, 30, 25)
    down_rect = pygame.Rect(list_x + 360, list_y + 30, 30, 25)

    pygame.draw.rect(screen, (100, 100, 150), up_rect)
    pygame.draw.rect(screen, (100, 100, 150), down_rect)

    up_text = font.render("▲", True, (255, 255, 255))
    down_text = font.render("▼", True, (255, 255, 255))
    screen.blit(up_text, (list_x + 367, list_y + 2))
    screen.blit(down_text, (list_x + 367, list_y + 32))

    return buy_rect, close_rect, (up_rect, down_rect)